In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import cross_validation, metrics
from sklearn.grid_search import GridSearchCV

import matplotlib.pylab as plt
%matplotlib inline
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 12, 4

/Library/Python/2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/Library/Python/2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

# 读取数据

In [64]:

train_url="/Users/leidelong/competition/Porto_Seguro_Safe_Driver_Prediction/train.csv"
train_raw=pd.read_csv(train_url)

test_url="/Users/leidelong/competition/Porto_Seguro_Safe_Driver_Prediction/test.csv"
test_raw=pd.read_csv(test_url)

# 数据探查

In [65]:
print "train shape:",train_raw.shape
print "test shape:",test_raw.shape
print "train columns:",train_raw.columns
print "test columns:",test_raw.columns

train shape: (595212, 59)
test shape: (892816, 58)
train columns: Index([u'id', u'target', u'ps_ind_01', u'ps_ind_02_cat', u'ps_ind_03',
       u'ps_ind_04_cat', u'ps_ind_05_cat', u'ps_ind_06_bin', u'ps_ind_07_bin',
       u'ps_ind_08_bin', u'ps_ind_09_bin', u'ps_ind_10_bin', u'ps_ind_11_bin',
       u'ps_ind_12_bin', u'ps_ind_13_bin', u'ps_ind_14', u'ps_ind_15',
       u'ps_ind_16_bin', u'ps_ind_17_bin', u'ps_ind_18_bin', u'ps_reg_01',
       u'ps_reg_02', u'ps_reg_03', u'ps_car_01_cat', u'ps_car_02_cat',
       u'ps_car_03_cat', u'ps_car_04_cat', u'ps_car_05_cat', u'ps_car_06_cat',
       u'ps_car_07_cat', u'ps_car_08_cat', u'ps_car_09_cat', u'ps_car_10_cat',
       u'ps_car_11_cat', u'ps_car_11', u'ps_car_12', u'ps_car_13',
       u'ps_car_14', u'ps_car_15', u'ps_calc_01', u'ps_calc_02', u'ps_calc_03',
       u'ps_calc_04', u'ps_calc_05', u'ps_calc_06', u'ps_calc_07',
       u'ps_calc_08', u'ps_calc_09', u'ps_calc_10', u'ps_calc_11',
       u'ps_calc_12', u'ps_calc_13', u'ps_calc_14', u'ps_calc_15_bin',
       u'ps_calc_16_bin', u'ps_calc_17_bin', u'ps_calc_18_bin',
       u'ps_calc_19_bin', u'ps_calc_20_bin'],
      dtype='object')
test columns: Index([u'id', u'ps_ind_01', u'ps_ind_02_cat', u'ps_ind_03', u'ps_ind_04_cat',
       u'ps_ind_05_cat', u'ps_ind_06_bin', u'ps_ind_07_bin', u'ps_ind_08_bin',
       u'ps_ind_09_bin', u'ps_ind_10_bin', u'ps_ind_11_bin', u'ps_ind_12_bin',
       u'ps_ind_13_bin', u'ps_ind_14', u'ps_ind_15', u'ps_ind_16_bin',
       u'ps_ind_17_bin', u'ps_ind_18_bin', u'ps_reg_01', u'ps_reg_02',
       u'ps_reg_03', u'ps_car_01_cat', u'ps_car_02_cat', u'ps_car_03_cat',
       u'ps_car_04_cat', u'ps_car_05_cat', u'ps_car_06_cat', u'ps_car_07_cat',
       u'ps_car_08_cat', u'ps_car_09_cat', u'ps_car_10_cat', u'ps_car_11_cat',
       u'ps_car_11', u'ps_car_12', u'ps_car_13', u'ps_car_14', u'ps_car_15',
       u'ps_calc_01', u'ps_calc_02', u'ps_calc_03', u'ps_calc_04',
       u'ps_calc_05', u'ps_calc_06', u'ps_calc_07', u'ps_calc_08',
       u'ps_calc_09', u'ps_calc_10', u'ps_calc_11', u'ps_calc_12',
       u'ps_calc_13', u'ps_calc_14', u'ps_calc_15_bin', u'ps_calc_16_bin',
       u'ps_calc_17_bin', u'ps_calc_18_bin', u'ps_calc_19_bin',
       u'ps_calc_20_bin'],
      dtype='object')

In [11]:
train_raw.isnull().any()

id                False
target            False
ps_ind_01         False
ps_ind_02_cat     False
ps_ind_03         False
ps_ind_04_cat     False
ps_ind_05_cat     False
ps_ind_06_bin     False
ps_ind_07_bin     False
ps_ind_08_bin     False
ps_ind_09_bin     False
ps_ind_10_bin     False
ps_ind_11_bin     False
ps_ind_12_bin     False
ps_ind_13_bin     False
ps_ind_14         False
ps_ind_15         False
ps_ind_16_bin     False
ps_ind_17_bin     False
ps_ind_18_bin     False
ps_reg_01         False
ps_reg_02         False
ps_reg_03         False
ps_car_01_cat     False
ps_car_02_cat     False
ps_car_03_cat     False
ps_car_04_cat     False
ps_car_05_cat     False
ps_car_06_cat     False
ps_car_07_cat     False
ps_car_08_cat     False
ps_car_09_cat     False
ps_car_10_cat     False
ps_car_11_cat     False
ps_car_11         False
ps_car_12         False
ps_car_13         False
ps_car_14         False
ps_car_15         False
ps_calc_01        False
ps_calc_02        False
ps_calc_03        False
ps_calc_04        False
ps_calc_05        False
ps_calc_06        False
ps_calc_07        False
ps_calc_08        False
ps_calc_09        False
ps_calc_10        False
ps_calc_11        False
ps_calc_12        False
ps_calc_13        False
ps_calc_14        False
ps_calc_15_bin    False
ps_calc_16_bin    False
ps_calc_17_bin    False
ps_calc_18_bin    False
ps_calc_19_bin    False
ps_calc_20_bin    False
dtype: bool

In [4]:
target='target'
IDcol = 'id'

train_raw['target'].value_counts()

0    573518
1     21694
Name: target, dtype: int64

In [5]:
train_pos=train_raw[train_raw['target']==1]
print train_pos['target'].value_counts()
train_neg=train_raw[train_raw['target']==0]
print train_neg['target'].value_counts()

1    21694
Name: target, dtype: int64
0    573518
Name: target, dtype: int64

In [6]:
#拆分数据集
from sklearn.cross_validation import train_test_split  

#df转narray
train_pos=np.array(train_pos)
train_neg=np.array(train_neg)
#数据集拆分
train_pos_new,test_pos_new = train_test_split(train_pos,  
                                                   test_size = 0.2,  
                                                   random_state = 0)  
train_neg_new,test_neg_new = train_test_split(train_neg,  
                                                   test_size = 0.2,  
                                                   random_state = 0)  
#数据集拼接
train_new=np.concatenate([train_pos_new,train_neg_new],axis=0) #在纵轴上合并
print train_new.shape

test_new=np.concatenate([test_pos_new,test_neg_new],axis=0) #在纵轴上合并
print test_new.shape

(476169, 59)
(119043, 59)

In [14]:
train_temp=pd.DataFrame(train_new)
train_temp.columns=train_raw.columns
train=train_temp

test_temp=pd.DataFrame(test_new)
test_temp.columns=train_raw.columns
test=test_temp

In [15]:
test.tail(10)

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
119033,334364,0,0,1,2,1,0,1,0,0,...,4,1,4,11,0,0,0,0,0,0
119034,1481857,0,1,1,10,0,0,1,0,0,...,4,2,1,5,0,1,1,0,1,0
119035,27692,0,5,1,5,1,3,1,0,0,...,3,0,2,6,0,1,0,0,1,0
119036,721072,0,1,2,1,0,0,0,0,0,...,10,1,5,10,0,1,1,0,1,0
119037,580805,0,3,2,5,1,0,0,1,0,...,4,1,8,8,0,1,0,0,0,0
119038,1321873,0,5,1,3,1,0,0,0,0,...,3,0,1,7,0,1,1,0,1,0
119039,928766,0,6,1,5,1,0,0,1,0,...,8,2,2,9,0,1,1,1,1,0
119040,673898,0,2,1,2,0,0,1,0,0,...,1,2,3,9,0,0,1,0,1,0
119041,520528,0,6,1,3,0,0,1,0,0,...,4,2,1,6,0,0,1,0,1,1
119042,772755,0,2,4,9,1,0,1,0,0,...,5,2,4,9,0,1,1,0,0,0

In [8]:
train.describe()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
count,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,...,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000,476169.000000
mean,743556.763846,0.036447,1.898675,1.359866,4.420355,0.416512,0.404606,0.394022,0.256842,0.163534,...,5.441028,1.440575,2.871823,7.539395,0.122816,0.627599,0.553763,0.287369,0.348868,0.153387
std,429281.111160,0.187400,1.983634,0.665183,2.701802,0.493262,1.349630,0.488640,0.436892,0.369853,...,2.333660,1.201702,1.694399,2.748612,0.328226,0.483445,0.497102,0.452535,0.476613,0.360360
min,7.000000,0.000000,0.000000,-1.000000,0.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,371786.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.000000,1.000000,2.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,742948.000000,0.000000,1.000000,1.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,5.000000,1.000000,3.000000,7.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,1115059.000000,0.000000,3.000000,2.000000,6.000000,1.000000,0.000000,1.000000,1.000000,0.000000,...,7.000000,2.000000,4.000000,9.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,1488027.000000,1.000000,7.000000,4.000000,11.000000,1.000000,6.000000,1.000000,1.000000,1.000000,...,19.000000,10.000000,13.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Define a function for modeling and cross-validation

This function will do the following:
1. fit the model
2. determine training accuracy
3. determine training AUC
4. determine testing AUC
5. update n_estimators with cv function of xgboost package
6. plot Feature Importance

# 不调整样本比例

In [25]:
predictors = [x for x in train.columns if x not in [target, IDcol]]
X = train[predictors]
y = train['target']
X_test = test[predictors]
y_test = test['target']

In [26]:
from sklearn.metrics import roc_auc_score
def gini(y_actual, y_pred):
  return 2*roc_auc_score(y_actual, y_pred)-1

In [27]:
gbm0 = GradientBoostingClassifier(random_state=10)
gbm0.fit(X,y)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=10,
              subsample=1.0, verbose=0, warm_start=False)

In [44]:

def model(gbm0,X,y,X_test,y_test):
    #训练集评测
    y_pred = gbm0.predict(X)
    y_predprob = gbm0.predict_proba(X)[:,1]
    print "Accuracy : %.4g" % metrics.accuracy_score(y.values, y_pred)
    print "AUC Score (Train): %f" % metrics.roc_auc_score(y, y_predprob)
    #GINI score
    print "GINI Score (Train): %f" % gini(y, y_predprob)

    #测试集评测
    y_test_pred = gbm0.predict(X_test)
    y_test_predprob = gbm0.predict_proba(X_test)[:,1]

    print "Accuracy : %.4g" % metrics.accuracy_score(y_test.values, y_test_pred)
    print "AUC Score (Test): %f" % metrics.roc_auc_score(y_test, y_test_predprob)
    #GINI score
    print "GINI Score (Test): %f" % gini(y_test, y_test_predprob)
    
model(gbm0,X,y,X_test,y_test)

Accuracy : 0.9636
AUC Score (Train): 0.648008
GINI Score (Train): 0.296015
Accuracy : 0.9635
AUC Score (Test): 0.639052
GINI Score (Test): 0.278105

# GridSearch 调参

In [38]:
X2 = train[predictors]
y2 = train['target']
X2_test = test[predictors]
y2_test = test['target']

In [47]:
#Grid seach on subsample and max_features
#Choose all predictors except target & IDcols

param_test1 = {'n_estimators':range(20,201,10)}
gsearch1 = GridSearchCV(estimator = GradientBoostingClassifier(learning_rate=0.1, subsample=0.8,random_state=10), 
                       param_grid = param_test1, scoring='roc_auc',iid=False,cv=5, n_jobs=-1)
gsearch1.fit(X2,y2)
gsearch1.grid_scores_, gsearch1.best_params_, gsearch1.best_score_

([mean: 0.62497, std: 0.00249, params: {'n_estimators': 20},
  mean: 0.62872, std: 0.00249, params: {'n_estimators': 30},
  mean: 0.63165, std: 0.00248, params: {'n_estimators': 40},
  mean: 0.63336, std: 0.00251, params: {'n_estimators': 50},
  mean: 0.63407, std: 0.00281, params: {'n_estimators': 60},
  mean: 0.63498, std: 0.00301, params: {'n_estimators': 70},
  mean: 0.63564, std: 0.00314, params: {'n_estimators': 80},
  mean: 0.63610, std: 0.00324, params: {'n_estimators': 90},
  mean: 0.63655, std: 0.00339, params: {'n_estimators': 100},
  mean: 0.63682, std: 0.00329, params: {'n_estimators': 110},
  mean: 0.63720, std: 0.00301, params: {'n_estimators': 120},
  mean: 0.63745, std: 0.00319, params: {'n_estimators': 130},
  mean: 0.63759, std: 0.00327, params: {'n_estimators': 140},
  mean: 0.63766, std: 0.00337, params: {'n_estimators': 150},
  mean: 0.63768, std: 0.00340, params: {'n_estimators': 160},
  mean: 0.63781, std: 0.00343, params: {'n_estimators': 170},
  mean: 0.63784, std: 0.00343, params: {'n_estimators': 180},
  mean: 0.63794, std: 0.00324, params: {'n_estimators': 190},
  mean: 0.63800, std: 0.00323, params: {'n_estimators': 200}],
 {'n_estimators': 200},
 0.6380005411813638)

In [49]:
estimator = GradientBoostingClassifier(n_estimators=200,learning_rate=0.1, random_state=10)
estimator.fit(X2,y2)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=200, presort='auto', random_state=10,
              subsample=1.0, verbose=0, warm_start=False)

In [53]:
model(estimator,X2,y2,X2_test,y2_test)

Accuracy : 0.9636
AUC Score (Train): 0.655550
GINI Score (Train): 0.311100
Accuracy : 0.9635
AUC Score (Test): 0.640722
GINI Score (Test): 0.281445

# unbalance

In [166]:
train['weight']=1
train.loc[train['target']==1, 'weight'] = 9
train.loc[train['target']==0, 'weight'] =1

In [167]:
X3 = train[predictors]
y3 = train['target']
X3_weight=train['weight']
X3_test = test[predictors]
y3_test = test['target']

In [168]:
train.tail(10)

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin,weight
476159,805737,0,1,2,0,1,4,0,1,0,...,0,4,9,0,0,0,1,0,1,1
476160,971312,0,3,1,2,0,0,0,0,0,...,3,2,10,0,1,0,0,0,0,1
476161,1162713,0,1,1,1,1,0,0,1,0,...,1,5,8,0,0,1,0,0,0,1
476162,318080,0,2,1,2,0,0,1,0,0,...,0,2,5,0,1,1,0,0,0,1
476163,788770,0,1,1,5,1,5,0,1,0,...,0,1,9,0,0,1,1,0,1,1
476164,933249,0,0,1,2,1,0,0,1,0,...,0,6,6,0,1,0,0,1,0,1
476165,395368,0,2,1,4,1,0,1,0,0,...,2,3,6,0,1,1,0,0,0,1
476166,306135,0,0,1,6,1,0,1,0,0,...,1,4,8,1,1,0,1,1,1,1
476167,1130619,0,4,1,6,0,0,1,0,0,...,2,2,9,0,0,1,1,1,0,1
476168,792871,0,3,2,2,0,0,1,0,0,...,0,3,6,0,1,1,0,0,0,1

In [169]:

estimator = GradientBoostingClassifier(n_estimators=200,learning_rate=0.1, random_state=10)
estimator.fit(X3,y3,X3_weight)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=200, presort='auto', random_state=10,
              subsample=1.0, verbose=0, warm_start=False)

In [170]:
model(estimator,X3,y3,X3_test,y3_test)

Accuracy : 0.9552
AUC Score (Train): 0.659923
GINI Score (Train): 0.319847
Accuracy : 0.9547
AUC Score (Test): 0.642665
GINI Score (Test): 0.285331

# 以下是最终测试数据效果

In [171]:
#最终测试集
X_test_raw= test_raw[predictors]
y_raw_test_pred = estimator.predict(X_test_raw)
y_raw_test_predprob=estimator.predict_proba(X_test_raw)[:,1]

In [172]:
y_raw_test_predprob

array([ 0.18782275,  0.22182204,  0.21141901, ...,  0.2728863 ,
        0.1808396 ,  0.19787469])

In [173]:
y_raw_test_predprob.shape

(892816,)

In [174]:
test_raw.head(10)

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1
5,5,0,1,6,0,0,1,0,0,0,...,8,1,4,9,1,0,1,0,1,0
6,6,0,1,3,0,0,0,1,0,0,...,2,0,4,6,1,1,0,0,0,0
7,8,0,1,0,0,0,1,0,0,0,...,3,1,4,9,0,1,0,0,0,0
8,10,0,1,7,0,0,0,1,0,0,...,5,1,4,6,0,0,1,0,0,0
9,11,1,1,6,0,0,0,0,0,1,...,6,1,6,10,0,1,1,0,0,0

In [175]:
X_ID = test_raw['id']
X_ID=pd.DataFrame(X_ID)
df_y_test_predprob=pd.DataFrame(y_raw_test_predprob)
print df_y_test_predprob.shape,X_ID.shape

(892816, 1) (892816, 1)

In [176]:
df_y_test_predprob.head(10)

          0
0  0.187823
1  0.221822
2  0.211419
3  0.122958
4  0.238073
5  0.265237
6  0.122583
7  0.240397
8  0.357182
9  0.362048

In [177]:
result=pd.concat([X_ID,df_y_test_predprob],axis=1)
result.columns = ['id', 'target']
result.shape

(892816, 2)

In [178]:
result.head(10)

   id    target
0   0  0.187823
1   1  0.221822
2   2  0.211419
3   3  0.122958
4   4  0.238073
5   5  0.265237
6   6  0.122583
7   8  0.240397
8  10  0.357182
9  11  0.362048

In [179]:
result.to_csv("/Users/leidelong/competition/Porto_Seguro_Safe_Driver_Prediction/test_result_2.csv",index=False)